image: tiangolo/docker-with-compose

services:
    - docker:dind

stages:
    - test

test:
    stage: test
    services: 
        - redis
    script:
        - cd api
        - pip install --upgrade pip
        - pip install flask flask_restful redis pytest
        - pytest -p no:cacheprovider tests

  