image: tiangolo/docker-with-compose

services:
    - docker:dind

stages:
    - build
    - test

build:
    stage: build
    script: 
        - docker-compose build

test:
    stage: test
    image: pss_assignment_1_api
    services: 
        - redis
    variables:
        - TESTING: 1
        - PYTHONDONTWRITEBYTECODE: 1
    script:
        - pytest -p no:cacheprovider tests

  