image: tiangolo/docker-with-compose:latest

variables:
    FLASK_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/flask:latest
    API_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/api:latest
    NGINX_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/nginx:latest
    FLASK_TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/flask:$CI_COMMIT_SHA
    API_TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/api:$CI_COMMIT_SHA
    NGINX_TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/nginx:$CI_COMMIT_SHA
    DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
    - build
    - test
    - push

build:
    stage: build
    services:
        - docker:dind
    script:
        - docker pull $FLASK_IMAGE || true
        - docker pull $NGINX_IMAGE || true
        - docker pull $API_IMAGE || true
        - docker build --cache-from $API_IMAGE -t $API_TEST_IMAGE api/
        - docker build --cache-from $FLASK_IMAGE -t $FLASK_TEST_IMAGE flask/
        - docker build --cache-from $NGINX_IMAGE -t $NGINX_TEST_IMAGE nginx/
        - docker push $API_TEST_IMAGE
        - docker push $FLASK_TEST_IMAGE
        - docker push $NGINX_TEST_IMAGE

test:
    stage: test
    before_script: 
        - ''
    services: 
        - redis
    script:
        - cd api
        - pip install --upgrade pip
        - pip install flask flask_restful redis pytest
        - pytest -p no:cacheprovider tests

push:
    stage: push
    services:
        - docker:dind
    script:
        - docker pull $FLASK_TEST_IMAGE || true
        - docker pull $NGINX_TEST_IMAGE || true
        - docker pull $API_TEST_IMAGE || true
        - docker tag $API_TEST_IMAGE $API_IMAGE 
        - docker tag $FLASK_TEST_IMAGE $FLASK_IMAGE
        - docker tag $NGINX_TEST_IMAGE $NGINX_IMAGE
        - docker push $API_IMAGE
        - docker push $FLASK_IMAGE
        - docker push $NGINX_IMAGE



  



  