image: tiangolo/docker-with-compose

variables:
    DOCKER_REGISTRY: registry.gitlab.com
    DOCKER_FLASK_IMAGE: registry.gitlab.com/lucabrena/pss_assignment_1/flask
    DOCKER_API_IMAGE: registry.gitlab.com/lucabrena/pss_assignment_1/api
    DOCKER_NGINX_IMAGE: registry.gitlab.com/lucabrena/pss_assignment_1/nginx


services:
    - docker:dind

stages:
    - build
    - test
    - push

build:
    stage: build
    script:
        - docker-compose build

test:
    stage: test
    services: 
        - redis
    script:
        - cd api
        - pip install --upgrade pip
        - pip install flask flask_restful redis pytest
        - pytest -p no:cacheprovider tests

push:
    stage: push
    services: 
        - docker:dind
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
        - docker build -t $DOCKER_FLASK_IMAGE flask/
        - docker build -t $DOCKER_API_IMAGE api/
        - docker build -t $DOCKER_NGINX_IMAGE nginx/
        - docker push $DOCKER_FLASK_IMAGE
        - docker push $DOCKER_API_IMAGE
        - docker push $DOCKER_NGINX_IMAGE



  