image: docker:latest

variables:
    DOCKER_REGISTRY: registry.gitlab.com
    DOCKER_FLASK_IMAGE: registry.gitlab.com/lucabrena/pss_assignment_1/flask
    DOCKER_API_IMAGE: registry.gitlab.com/lucabrena/pss_assignment_1/api
    DOCKER_NGINX_IMAGE: registry.gitlab.com/lucabrena/pss_assignment_1/nginx


stages:
    - build
    - test
    - push

build:
    stage: build
    script:
        - docker build\
            --cache-from api:latest\
            --tag api:$CI_BUILD_REF\
            --tag api:latest\
        - docker build\
            --cache-from flask:latest\
            --tag flask:$CI_BUILD_REF\
            --tag flask:latest\
        - docker build\
            --cache-from nginx:latest\
            --tag nginx:$CI_BUILD_REF\
            --tag nginx:latest\

test:
    stage: test
    services: 
        - redis
    script:
        - cd api
        - pip install --upgrade pip
        - pip install flask flask_restful redis pytest
        - pytest -p no:cacheprovider tests

push:
    stage: push
    script:
        - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
        # - docker build -t $DOCKER_FLASK_IMAGE flask/
        # - docker build -t $DOCKER_API_IMAGE api/
        # - docker build -t $DOCKER_NGINX_IMAGE nginx/
        - docker push nginx
        - docker push flask
        - docker push api



  