image: docker:latest

variables:
    FLASK_DEPLOY_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/kubernetes/deploy/flask:latest
    API_DEPLOY_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/kubernetes/deploy/api:latest
    NGINX_DEPLOY_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/kubernetes/deploy/nginx:latest

    FLASK_DEV_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/kubernetes/dev/flask
    API_DEV_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/kubernetes/dev/api
    NGINX_DEV_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/kubernetes/dev/nginx

    DOCKER_DEV_ENV_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/env/test-env:latest
    
    DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
    - build
    - test
    - push
    - release

build-api:
    stage: build
    services:
        - docker:dind
    script:
        - docker pull $API_DEV_IMAGE || true
        - docker build --cache-from $API_DEV_IMAGE -t $API_DEV_IMAGE:$CI_COMMIT_SHA api/
        - docker push $API_DEV_IMAGE:$CI_COMMIT_SHA

build-flask:
    stage: build
    services:
        - docker:dind
    script:
        - docker pull $FLASK_DEV_IMAGE || true
        - docker build --cache-from $FLASK_DEV_IMAGE -t $FLASK_DEV_IMAGE:$CI_COMMIT_SHA flask/
        - docker push $FLASK_DEV_IMAGE:$CI_COMMIT_SHA

build-nginx:
    stage: build
    services:
        - docker:dind
    script:
        - docker pull $NGINX_DEV_IMAGE || true
        - docker build --cache-from $NGINX_DEV_IMAGE -t $NGINX_DEV_IMAGE:$CI_COMMIT_SHA nginx/
        - docker push $NGINX_DEV_IMAGE:$CI_COMMIT_SHA

build-test-env:
    stage: build
    services:
        - docker:dind
    script:
        - docker pull $DOCKER_DEV_ENV_IMAGE
        - docker build --cache-from $DOCKER_DEV_ENV_IMAGE -t $DOCKER_DEV_ENV_IMAGE tests/
        - docker push $DOCKER_DEV_ENV_IMAGE

test:
    stage: test
    image: $DOCKER_DEV_ENV_IMAGE
    before_script: 
        - ''
    services: 
        - redis
    script:
        - pytest -p no:cacheprovider tests

push-api:
    stage: push
    services:
        - docker:dind
    script:
        - docker pull $API_DEV_IMAGE:$CI_COMMIT_SHA
        - docker tag $API_DEV_IMAGE:$CI_COMMIT_SHA $API_DEV_IMAGE:latest
        - docker push $API_DEV_IMAGE:latest

push-flask:
    stage: push
    services:
        - docker:dind
    script:
        - docker pull $FLASK_DEV_IMAGE:$CI_COMMIT_SHA
        - docker tag $FLASK_DEV_IMAGE:$CI_COMMIT_SHA $FLASK_DEV_IMAGE:latest
        - docker push $FLASK_DEV_IMAGE:latest

push-nginx:
    stage: push
    services:
        - docker:dind
    script:
        - docker pull $NGINX_DEV_IMAGE
        - docker tag $NGINX_DEV_IMAGE:$CI_COMMIT_SHA $NGINX_DEV_IMAGE:latest
        - docker push $NGINX_DEV_IMAGE:latest

release-api:
    stage: release
    services:
        - docker:dind
    only:
        - kubernetes
    script:
        - docker pull $API_DEV_IMAGE
        - docker tag $API_DEV_IMAGE $API_DEPLOY_IMAGE
        - docker push $API_DEPLOY_IMAGE

release-flask:
    stage: release
    services:
        - docker:dind
    only:
        - kubernetes
    script:
        - docker pull $FLASK_DEV_IMAGE
        - docker tag $FLASK_DEV_IMAGE $FLASK_DEPLOY_IMAGE
        - docker push $FLASK_DEPLOY_IMAGE

release-nginx:
    stage: release
    services:
        - docker:dind
    only:
        - kubernetes
    script:
        - docker pull $NGINX_DEV_IMAGE
        - docker tag $NGINX_DEV_IMAGE $NGINX_DEPLOY_IMAGE
        - docker push $NGINX_DEPLOY_IMAGE



  



  