image: tiangolo/docker-with-compose

services:
    - docker:dind

stages:
    - test

test:
    stage: test
    services: 
        - redis
    variables:
        TESTING: "1"
        PYTHONDONTWRITEBYTECODE: "1"
    script:
        - pytest -p no:cacheprovider tests

  