image: tiangolo/docker-with-compose:latest

variables:
    DOCKER_FLASK_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/flask
    DOCKER_API_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/api
    DOCKER_NGINX_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/nginx
    DOCKER_DRIVER: overlay2

services:
    - docker:dind

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
    - build
    # - test
    - push

build:
    stage: build
    script:
        - docker pull $DOCKER_FLASK_IMAGE:latest || true
    #     - docker pull $DOCKER_NGINX_IMAGE:latest || true
    #     - docker pull $DOCKER_API_IMAGE:latest || true
    #     - docker build --cache-from $DOCKER_API_IMAGE:latest -t $DOCKER_API_IMAGE:latest api/
        - docker build --cache-from $DOCKER_FLASK_IMAGE:latest -t $DOCKER_FLASK_IMAGE:prova flask/
    #     - docker build --cache-from $DOCKER_NGINX_IMAGE:latest -t $DOCKER_NGINX_IMAGE:latest nginx/
    artifacts:
        paths:
        - /var/lib/docker
    
# test:
#     stage: test
#     services: 
#         - redis
#     script:
#         - cd api
#         - pip install --upgrade pip
#         - pip install flask flask_restful redis pytest
#         - pytest -p no:cacheprovider tests

push:
    stage: push
    script:
        # - docker pull $DOCKER_FLASK_IMAGE:latest || true
        # - docker pull $DOCKER_NGINX_IMAGE:latest || true
        # - docker pull $DOCKER_API_IMAGE:latest || true
        # - docker build --cache-from $DOCKER_API_IMAGE:latest -t $DOCKER_API_IMAGE:latest api/
        # - docker build --cache-from $DOCKER_FLASK_IMAGE:latest -t $DOCKER_FLASK_IMAGE:latest flask/
        # - docker build --cache-from $DOCKER_NGINX_IMAGE:latest -t $DOCKER_NGINX_IMAGE:latest nginx/
        # - docker push $DOCKER_API_IMAGE:latest
        # - docker push $DOCKER_FLASK_IMAGE:latest
        - docker push $DOCKER_FLASK_IMAGE:prova



  



  