image: tiangolo/docker-with-compose:latest

variables:
    DOCKER_FLASK_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/flask:latest
    DOCKER_API_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/api:latest
    DOCKER_NGINX_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/nginx:latest

services:
    - docker:dind

stages:
    - build
    # - test
    # - push

cache:
  paths:
    - images/

build:
    stage: build
    script:
        - docker pull $DOCKER_FLASK_IMAGE || true
        - docker pull $DOCKER_NGINX_IMAGE || true
        - docker pull $DOCKER_API_IMAGE || true
        # - docker build --cache-from $CONTAINER_IMAGE:latest --tag $CONTAINER_IMAGE:$CI_COMMIT_SHA --tag $CONTAINER_IMAGE:latest .
        # - docker push $CONTAINER_IMAGE:$CI_COMMIT_SHA
        # - docker push $CONTAINER_IMAGE:latest
        # - docker build --cache-from $DOCKER_API_IMAGE:latest --tag $DOCKER_API_IMAGE:$CI_BUILD_REF --tag $DOCKER_API_IMAGE:latest api/
        # - docker build --cache-from $DOCKER_FLASK_IMAGE:latest --tag $DOCKER_FLASK_IMAGE:$CI_BUILD_REF --tag $DOCKER_FLASK_IMAGE:latest flask/
        # - docker build --cache-from $DOCKER_NGINX_IMAGE:latest --tag $DOCKER_NGINX_IMAGE:$CI_BUILD_REF --tag $DOCKER_NGINX_IMAGE:latest nginx/

# test:
#     stage: test
#     services: 
#         - redis
#     script:
#         - cd api
#         - pip install --upgrade pip
#         - pip install flask flask_restful redis pytest
#         - pytest -p no:cacheprovider tests

# push:
#     stage: push
#     services: 
#         - docker:dind
#     script:
#         - docker login -u gitlab-ci-token -p $CI_BUILD_TOKEN $DOCKER_REGISTRY
#         - docker push $DOCKER_FLASK_IMAGE:latest
#         - docker push $DOCKER_API_IMAGE:latest
#         - docker push $DOCKER_NGINX_IMAGE:latest



  



  