image: tiangolo/docker-with-compose

services:
    - docker:dind

stages:
    - build
    - test

build:
    stage: build
    script:
        - docker-compose build

test:
    stage: test
    services: 
        - redis
    script:
        - cd api
        - pip install --upgrade pip
        - pip install flask flask_restful redis pytest
        - pytest -p no:cacheprovider tests

  