image: tiangolo/docker-with-compose

services:
  - docker:dind

stages:
    - build
    - test

build:
  stage: build
  script: 
    - docker-compose build

test:
    stage: test
    script:
        - pip install --upgrade pip
        - pip install pytest
        - pytest tests

  