image: docker:latest

variables:
    FLASK_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/deploy/flask:latest
    API_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/deploy/api:latest
    NGINX_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/deploy/nginx:latest
    FLASK_TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/test/flask:$CI_COMMIT_SHA
    API_TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/test/api:$CI_COMMIT_SHA
    NGINX_TEST_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/test/nginx:$CI_COMMIT_SHA
    DOCKER_TEST_ENV_IMAGE: $CI_REGISTRY/$CI_PROJECT_PATH/env/test-env:latest
    DOCKER_DRIVER: overlay2

before_script:
  - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

stages:
    - build
    - test
    - push

build-api:
    stage: build
    services:
        - docker:dind
    script:
        - docker pull $API_IMAGE
        - docker build --cache-from $API_IMAGE -t $API_TEST_IMAGE api/
        - docker push $API_TEST_IMAGE

build-flask:
    stage: build
    services:
        - docker:dind
    script:
        - docker pull $FLASK_IMAGE
        - docker build --cache-from $FLASK_IMAGE -t $FLASK_TEST_IMAGE flask/
        - docker push $FLASK_TEST_IMAGE

build-nginx:
    stage: build
    services:
        - docker:dind
    script:
        - docker pull $NGINX_IMAGE
        - docker build --cache-from $NGINX_IMAGE -t $NGINX_TEST_IMAGE nginx/
        - docker push $NGINX_TEST_IMAGE

build-test-env:
    stage: build
    services:
        - docker:dind
    script:
        - docker pull $DOCKER_TEST_ENV_IMAGE
        - docker build --cache-from $DOCKER_TEST_ENV_IMAGE -t $DOCKER_TEST_ENV_IMAGE tests/
        - docker push $DOCKER_TEST_ENV_IMAGE

test:
    stage: test
    image: $DOCKER_TEST_ENV_IMAGE
    before_script: 
        - ''
    services: 
        - redis
    script:
        - pytest -p no:cacheprovider tests

push-api:
    stage: push
    services:
        - docker:dind
    script:
        - docker pull $API_TEST_IMAGE || true
        - docker tag $API_TEST_IMAGE $API_IMAGE
        - docker push $API_IMAGE

push-flask:
    stage: push
    services:
        - docker:dind
    script:
        - docker pull $FLASK_TEST_IMAGE || true
        - docker tag $FLASK_TEST_IMAGE $FLASK_IMAGE
        - docker push $FLASK_IMAGE

push-nginx:
    stage: push
    services:
        - docker:dind
    script:
        - docker pull $NGINX_TEST_IMAGE || true
        - docker tag $NGINX_TEST_IMAGE $NGINX_IMAGE
        - docker push $NGINX_IMAGE



  



  