# docker-compose.yml
version: '3'

services:
  flask:
    build:
      context: $PWD/webapp/
      dockerfile: $PWD/webapp/Dockerfile
    volumes:
      # For development only
      - $PWD/webapp/:/webapp/
    depends_on:
      - redis

  nginx:
    image: webapp-nginx
    build:
      context: $PWD/nginx
      dockerfile: $PWD/nginx/Dockerfile
    ports:
      - 5454:80
    depends_on:
      - flask
    volumes:
      # For development only
      - $PWD/nginx/html/:/usr/share/nginx/html/

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:  
  redis_data:
