# docker-compose.yml
version: '3'

services:
  api:
    build:
      context: $PWD/api/
      dockerfile: $PWD/api/Dockerfile
    volumes:
      # For development only
      - $PWD/api/:/api/
    depends_on:
      - redis

  flask:
    build:
      context: $PWD/webapp/
      dockerfile: $PWD/webapp/Dockerfile
    volumes:
      # For development only
      - $PWD/webapp/:/webapp/
    depends_on:
      - api

  nginx:
    build:
      context: $PWD/nginx
      dockerfile: $PWD/nginx/Dockerfile
    ports:
      - 80:80
    depends_on:
      - flask
      - api
    volumes:
      # For development only
      - $PWD/nginx/html/:/usr/share/nginx/html/

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data

volumes:  
  redis_data:
