apiVersion: apps/v1beta1
kind: Deployment
metadata:
  # Unique key of the Deployment instance
  name: api-deployment
spec:
  # 1 Pod should exist at all times.
  replicas: 1
  template:
    metadata:
      labels:
        # Apply this label to pods and default
        # the Deployment label selector to this value
        app: api-pod
    spec:
      containers:
        - name: api-container
          image: webapp-api:kuber
          ports:
            - name: http-api
              containerPort: 7000
            - name: wsgi-api
              containerPort: 6000